---
fixtures:
  symlinks:
    sensu_handlers: "#{source_dir}"
  repositories:
    monitoring_check: "https://github.com/Yelp/puppet-monitoring_check"
    sensu: "https://github.com/sensu/sensu-puppet"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
