---
language: ruby
bundler_args: --without development
before_install:
  - gem install bundler --version "< 2.0"
  - rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.1.0
script: bundle exec rake spec
env:
  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
