---
language: ruby
bundler_args: --without development
before_install:
  - gem install bundler
  - rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake spec
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.2.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
